# Use the redhattraining/hello-world-nginx image as the base image
FROM quay.io/redhattraining/hello-world-nginx:latest

# Copy your custom index.html to the nginx html directory
COPY index.html /usr/share/nginx/html/

# Expose port 80
EXPOSE 8080
