---
- name: Display kubeconfig file
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Print kubeconfig file contents
      shell: cat "{{ kubeconfig_path }}"
      register: kubeconfig_file

    - name: Display kubeconfig file content
      debug:
        var: kubeconfig_file.stdout_lines

- name: Deploy NGINX to Kubernetes
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Create NGINX Deployment
      command: kubectl apply -f kubemanifest/deployment.yaml --kubeconfig={{ kubeconfig_path }}
