- name: Deploy NGINX to Kubernetes
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Create NGINX Deployment
      k8s:
        state: present
        definition: "{{ lookup('file', 'kubemanifest/deployment.yaml') }}"
  tags: always  # Add tags to ensure the playbook always runs
  verbosity: 3  # Enable verbose output
