---
- name: Deploy NGINX to Kubernetes
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Create NGINX Deployment
      k8s:
        state: present
        definition: "{{ lookup('file', 'kubemanifest/deployment.yaml') }}"
