---
- name: Deploy Application to Kubernetes
  hosts: localhost
  tasks:
    - name: Apply test deployment
      command: kubectl apply -f deployment.yaml --kubeconfig=kubeconfig.yaml

    # Apply Kubernetes Service
    - name: Apply Kubernetes Service
      command: kubectl apply -f nginx-service.yaml --kubeconfig=kubeconfig.yaml

